"""
export_demo_bundle.py — Capture current DB quiz banks into demo_quiz_bundle.json.

Run this ONCE on a machine with a populated studyaid.db (after running seed_demo.py
with internet, so all 16 Gemini banks are in the DB). The output is committed to
the repo and used by the offline "Isi Data Demo" button in /admin/settings.

Usage (from inside companion/ with venv active):
    python export_demo_bundle.py

Overwrites companion/data/demo_quiz_bundle.json.
Safe to run multiple times — always captures the current DB state.
"""

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from app import create_app
from models.schema import Subject, QuizBank, QuizQuestion, TopicDeadline

app = create_app()

BUNDLE_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                           "data", "demo_quiz_bundle.json")

# Topic→profile mapping from seed_demo.py  (needed for the bundle metadata)
_TOPIC_PROFILES = {}
try:
    from demo_seed import KHALISH_TOPICS, RANIA_TOPICS
    for (subj, topic, profile, *_) in KHALISH_TOPICS + RANIA_TOPICS:
        _TOPIC_PROFILES[(subj, topic)] = profile
except ImportError:
    pass  # graceful — profile field will be empty string if missing


def main():
    with app.app_context():
        banks = QuizBank.query.all()
        if not banks:
            print("ERROR: No quiz banks in DB. Run seed_demo.py first.")
            sys.exit(1)

        bundle_banks = []
        for bank in banks:
            subject = Subject.query.get(bank.subject_id)
            questions = QuizQuestion.query.filter_by(bank_id=bank.id).all()
            if not questions:
                print(f"  [SKIP] No questions for {subject.name_bm} / {bank.topic}")
                continue

            profile = _TOPIC_PROFILES.get((subject.name_bm, bank.topic), "")
            bundle_banks.append({
                "subject_name_bm": subject.name_bm,
                "topic":           bank.topic,
                "profile":         profile,
                "questions": [
                    {
                        "question_text": q.question_text,
                        "options":       json.loads(q.options_json),
                        "correct_index": q.correct_index,
                        "language":      q.language,
                        "difficulty":    q.difficulty,
                    }
                    for q in questions
                ],
            })
            print(f"  [OK]  {subject.name_bm} / {bank.topic} — {len(questions)} soalan")

        os.makedirs(os.path.dirname(BUNDLE_PATH), exist_ok=True)
        with open(BUNDLE_PATH, "w", encoding="utf-8") as f:
            json.dump({
                "version": 1,
                "note": (
                    "Offline quiz bundle for the StudyAid booth. "
                    "Generated by export_demo_bundle.py from a live DB. "
                    "Do not edit manually — re-run export_demo_bundle.py to refresh."
                ),
                "banks": bundle_banks,
            }, f, ensure_ascii=False, indent=2)

        print(f"\nExported {len(bundle_banks)} banks to {BUNDLE_PATH}")


if __name__ == "__main__":
    main()
